- .gitignore
- requirements.txt
- result/html_reporter.py
- result/reporter.py
- test/test_html_reporter.py
- test/test_reporter.py
- test/test_suite_runner.py
- test_suite/cloud/test_aws.py
- test_suite/generic/test_generic.py
- test_suite/suite_runner.py
Also added basic tests migrated from ami-val module.
> Added code base for test runner and reporter.

- cloud/terraform/sample/resources.json
- cloud/terraform/terraform_configurator.py
- cloud/terraform/terraform_controller.py
- requirements.txt
- test/test_suite_runner.py
- test_suite/cloud/test_aws.py
- test_suite/generic/test_generic.py
- test_suite/suite_runner.py
Also added test cases migrated from ami-val module.
> Improved Terraform modules and suite runner.

- cloud/terraform/terraform_controller.py
- test/test_terraform_controller.py
add terraform controller unit tests
> terraform controller unit tests

- .github/workflows/ci.yml
- cloud/terraform/terraform_configurator.py
- main/cloud_image_validator.py
- requirements.txt
- test/test_cloud_image_validator.py
- test/test_suite_runner.py
in order to apply pep8 standard. We are incorporating flake 8 to our CI pipeline
> add python linter

- README.md
- cloud-image-val.py
- main/cloud_image_validator.py
- test/test_cloud_image_validator.py
- test/test_suite_runner.py
- test_suite/suite_runner.py
Minor improvements in README.md.
> Added test filtering capability to main script.

- main/cloud_image_validator.py
- test/test_suite_runner.py
- test_suite/suite_runner.py
Also improved failed test retry filter and added pprint of the generated instances in cloud_image_validator.
> Improved suite runner to use default connectionr (paramiko)

- cloud-image-val.py
- main/cloud_image_validator.py
- requirements.txt
- test/test_cloud_image_validator.py
- test/test_suite_runner.py
- test_suite/conftest.py
- test_suite/suite_runner.py
And fixed an issue with relative import of a module.
> Improved html reporting

- cloud-image-val.py
- test_suite/cloud/test_aws.py
- test_suite/generic/test_generic.py
Migrated two basic tests from ami-val
> migrated two tests from ami-val project

- test_suite/cloud/test_aws.py
Also added a fixture for AWS instances data to be obtained from their web service.
> Migrated two tests.

- test_suite/cloud/test_aws.py
- test_suite/conftest.py
Also migrated one more test case from ami-val.
> Improved HTML report by adding "Image Reference" for each test case.

- test_suite/generic/test_generic.py
Two new tests migrated:
- test_bash_in_shell_config
- test_root_is_locked
> add two new tests

- test_suite/generic/test_generic.py
> added test_sysconfig_kernel

- cloud/sample/resources_aws.json
- test/test_suite_runner.py
- test_suite/cloud/test_aws.py
- test_suite/conftest.py
- test_suite/generic/test_generic.py
Added new fixture to deal with RHEL SAP-only images.
> Migrated 5 tests from ami-val.

- cloud-image-val.py
- main/cloud_image_validator.py
- test/test_cloud_image_validator.py
- test_suite/suite_runner.py
the exit code from cloud-image-val was always 0.
> exit code should be 1 if any test fails

- pytest.ini
- test_suite/cloud/test_aws.py
- test_suite/generic/test_generic.py
> Migrated test_stage1_check_ena_set_in_image and test_grub_config

- pytest.ini
- test_suite/cloud/test_aws.py
- test_suite/conftest.py
- test_suite/generic/test_generic.py
by adding run_on mark on each test, we can specify in which
distributions and versions that test should be run on.
> specify distro and version each test should be run on

- cloud/terraform/aws_config_builder.py
- cloud/terraform/azure_config_builder.py
- cloud/terraform/base_config_builder.py
- cloud/terraform/terraform_configurator.py
- cloud/terraform/terraform_controller.py
- main/cloud_image_validator.py
- test/test_terraform_controller.py
- test_suite/conftest.py
Minor improvements when stopping cleanup: Now we print the ssh commands to use for each image name.
> Changed logic of randomizing resource names.

- .github/workflows/ci.yml
augment CIV CI by executing the tests in the images on the sample json.
This is just a PoC for now.
> execute tests in sample images

- test_suite/cloud/test_aws.py
- test_suite/generic/test_generic.py
Also fixed a false positive in cpu flags test case.
> Migrated some more test cases from ami-val.

- test_suite/generic/test_generic.py
test_no_sshkeys_knownhosts -> test_no_sshkeys_knownhosts
> add os-test tests

- test_suite/cloud/test_aws.py
Signed-off-by: Xiao Liang <xiliang@redhat.com>
> aws: added qemu-guest-agent to unwanted list for bz2075815

- test_suite/cloud/test_aws.py
- test_suite/generic/test_generic.py
More details in commit messages
> Solve various errors

- test_suite/generic/test_generic.py
This is to comply with Azure requirements.
> Adapted two generic tests already migrated from ami-val.

- .gitlab-ci.yml
This applies to jobs for active PRs and main (when a merge occurred).
When there is a merge, container with the 'latest' tag will be updated.
In all cases, the branch-specific container will be built/updated.
> Added build and push of the updated container.

- test_suite/cloud/test_azure.py
- test_suite/generic/test_generic.py
- test_check_waagent_resourcedisk_format
- test_check_pkg_wanted
- test_check_networkmanager_conf
> Migrated test cases from os-tests.

- data/generic/fingerprint-auth_rhel7
- data/generic/fingerprint-auth_rhel8
- data/generic/fingerprint-auth_rhel9
- data/generic/password-auth_rhel7
- data/generic/password-auth_rhel8
- data/generic/password-auth_rhel9
- data/generic/postlogin_rhel7
- data/generic/postlogin_rhel8
- data/generic/postlogin_rhel9
- data/generic/smartcard-auth_rhel7
- data/generic/smartcard-auth_rhel8
- data/generic/smartcard-auth_rhel9
- data/generic/system-auth_rhel7
- data/generic/system-auth_rhel8
- data/generic/system-auth_rhel9
- test_suite/generic/test_generic.py
- test_check_authselect
- test_check_authselect_conf
- test_check_fingerprint_auth
- test_check_password_auth
- test_check_postlogin
- test_check_smartcard_auth
- test_check_system_auth
> Migrated 7 test cases related to auth config and file contents.

- test_suite/cloud/test_azure.py
> test_grub_params only applies to published images

- .gitlab-ci.yml
To do so, the easiest way is to use 'buildx' command prom docker
> CI: build multi arch container images

- test_suite/cloud/test_azure.py
add specific configuration for fedora
> test_suite: fix pwquality conf test in fedora

- lib/test_lib.py
- test_suite/generic/test_generic.py
this test is failing on aarch64 machines. print more information in test so we can debug what's happening
> test_suite: try to debug first_boot_time errors

- test_suite/generic/test_generic.py
Add new test case based on BugZilla 2127969.
> test_suite: add new test case for extra public keys

- test_suite/generic/test_generic.py
> test_suite: disable reboot tests

- .gitlab-ci.yml
- cloud/sample/resources_aws_marketplace.json
Testing with a marketplace AWS image, recently published.
> Added cloudx AWS account to the gitlab-ci file.

- lib/test_lib.py
- test_suite/cloud/test_azure.py
- test_suite/generic/test_generic.py
Also fixed SAP image detection in test_lib.
> Fixed SAP-related test cases for Azure vhd blobs and more.

- test_suite/generic/test_generic.py
- test_suite/generic/test_reboot.py
https://issues.redhat.com/browse/CLOUDX-241
> CIV: Move reboot and boot tests to a separate test suite file

- test_suite/cloud/test_azure.py
https://issues.redhat.com/browse/CLOUDX-259
> CIV: Refactor test_66_azure_storage_rules_file_content

- test_suite/conftest.py
Many tests needed to be skipped by bigger or smaller versions, this should simplify this operation.
Another approach to this is to get the version release in the init part of the code and use the 'skipif' builtin fixture - think this would be a better way to to this.
> CIV: Extend skip marker

- test_suite/conftest.py
> CIV: fix exclude_on marker

- test_suite/cloud/test_aws.py
The test cases fixed are:
- test_blocklist
- test_unwanted_packages_are_not_present
- test_required_packages_are_installed
> Fix test cases related to packages.

- main/civ_report_analyzer.py
This is to give a brief summary and insights of the report generated after running tests. This analyzer tool digests any report.json generated by CIV after running tests on cloud instances. It is an independent tool and can be used after running cloud-image-val main script.
> Added CIV Report Analyer tool.

- .gitlab-ci.yml
the export in the `script` section is not working. Debug this and fix this
> Variables are not correctly sent to test files

- README.md
- base.Dockerfile
When we changed CIV home, our jenkins broke. So going back to the old home even it's not that nice.
> Change default CIV home

- README.md
- pytest.ini
- requirements.txt
- test_suite/conftest.py
- test_suite/generic/test_markers.py
Added a new marker that lets you skip a test if a Jira ticket is not closed (can be more than one)
I also refactored the code to make it easier to read
> Jira skip marker

- cloud/terraform/aws_config_builder.py
- test_suite/generic/test_generic.py
This test needs more context to help debugging. Also add contact information.
> Show context in kdump test

- main/civ_report_analyzer.py
Enhanced the analyzer "table" output option to print more fields that fit into the "Execution Analysis" spreadsheet.
> CIV Report Analyzer improvements. 

- test_suite/cloud/test_azure.py
Starting from 9.2 version of the azure rhui rpm, the certificate got renamed. The logic was improved to comply with this and also check if the certificate exists first.
> Updated test_rhui_certificate_date test case to find rhui 9.2 cert.

- test_suite/cloud/test_aws.py
Add context to test and reenable it
> Reenable test in rhel 8.4

- test_suite/generic/test_generic.py
Also added more context to the test_sshd test case stdout.
About test_smartcard_auth test case, it will now be skipped until a Bugzilla is fixed and a release is done for that, affecting RHEL 8.9.
> Fixed test_sshd test case which was failing in RHEL 9.3 and 8.9.

- test_suite/generic/test_generic.py
And renamed it to test_network_manager_conf_plugins
> Fixed test_networkmanager_conf_plugins

- cloud/terraform/terraform_configurator.py
- main/cloud_image_validator.py
- test_suite/cloud/test_aws.py
Also added a minor improvement when dumping JSON artifacts.
> Fixed test rhui packages test case.

- test_suite/cloud/test_azure.py
Fix to check possible different cert files.
> Fixed test_rhui_certificate_date test case

- cloud/terraform/azure_config_builder_v2.py
Default will be "V2" if no value is provided or if it is null/empty.
Also improved VM name based on image name when it is available.
> Added support to specify HyperV generation in resources.json.

- cloud/terraform/azure_config_builder_v2.py
- cloud/terraform/base_config_builder.py
Thi will help us debug boot issues not detected by the Activity Log or terraform.
> Enable boot diagnostics for Azure VMs provisioned by the tool.

- test_suite/cloud/test_aws.py
The test case now outputs the exact version of the unwanted package that is installed.
> Improved test_unwanted_packages_are_not_present output.

- .gitlab-ci.yml
- Schutzfile
- ci/aws.sh
- ci/provision.sh
- ci/set-env-variables.sh
- ci/shared_lib.sh
- schutzbot/append_team_ssh_keys.sh
- schutzbot/get_civ_config.py
- test_suite/package/test_efs_utils.py
We introduce a new job in .gitlab-ci.yml. It is about enabling the CloudX team to run it on-demand, and install packages in AWS AMIs to be built by the CI. This will unblock us in many ways, and we will be able to automatically test new packages we plan to add to RHEL from now on.
This is not a final solution, since we must build our own CI infrastructure as a definitive solution.
> Implemented packages testing automation

- test_suite/cloud/test_azure.py
Now it checks for smaller size due to recent changes.
> Fixed test_osdisk_size test case.

- .gitlab-ci.yml
- ci/aws.sh
- cloud/opentofu/aws_config_builder.py
- main/civ_report_analyzer.py
Also modified the ci/aws.sh file to benefit from spot instances.
> Add aws spot instance deployment

- test_suite/package/test_awscli2.py
> Added awscli2 package test suite.

- test_suite/generic/test_generic.py
https://issues.redhat.com/browse/CLOUDX-978
> Fix for kdump issue

- test_suite/generic/test_generic.py
> CIV: Refactor flaky TC of no failing serivces

- Schutzfile
https://github.com/osbuild/osbuild-composer/blob/main/Schutzfile
> Changed Schutzfile file in CIV according to

- base.Dockerfile
- cloud/opentofu/azure_config_builder_v2.py
> Update OpenTofu binary and AZ provider.

- Schutzfile
Update osbuild/images commit to match osbuild-composer [PR4686](https://github.com/osbuild/osbuild-composer/pull/4686)
> update osbuild/images commit

- data/generic/fingerprint-auth_rhel10
- data/generic/password-auth_rhel10
- data/generic/postlogin_rhel10
- data/generic/smartcard-auth_rhel10
- data/generic/system-auth_rhel10
This adds expected pam files to test authselect configuration on Azure RHEL10.
> add expected authselect pam files

- test_suite/generic/test_generic.py
- `@pytest.mark.exclude_on(['rhel7.9'])` removed as we don't ship 7.9 anymore
- `@pytest.mark.jira_skip(['CLOUDX-511'])` as it was for 8.9 which we don't ship anymore
- altering authselect profile test for RHEL10 as it has a local profile by default as in [Beta docs](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/10-beta/html-single/10.0_beta_release_notes/index#new-features-and-enhancements-sssd)
- skipping pam files check for RHEL10 for now, as we need to confirm their changes in RHEL10
> update authselect tests for RHEL10

- test_suite/generic/test_generic.py
This changes a `test_eth0_network_adapter_setup` test to check for the NetworkManager keyfile plugin instead of the cfcfg file on RHEL10 and CentOS10.
> add keyfile plugin check for rhel10 and centos10

- test_suite/generic/test_generic.py
> Remove skip logic for RHEL-9.4 in test_no_avc_denials
