cloud/terraform/sample/resources.json, cloud/terraform/terraform_configurator.py, cloud/terraform/terraform_controller.py
to execute tests we need access to the generated instances via ssh.
Added functionality so new resources of type `aws_key_pair` are created,
one per region. Then, each instance get's this key added.
=> import ssh key pairs to aws via terraform

cloud/terraform/terraform_controller.py, lib/console_lib.py, main/cloud_image_validator.py, test/test_cloud_image_validator.py, test/test_terraform_controller.py
terraform commands output can be very big and hard to read. Add a debug
option so the full ouput can be skipped.
Also organize cloud-image-val output in different sections
=> Optimize cli output

cloud/terraform/aws_config_builder.py, cloud/terraform/azure_config_builder.py, cloud/terraform/base_config_builder.py
Without any random part to a resource name, cloud-image-val can only be
executed one at a time
=> add random string to each resource

test_suite/generic/test_generic.py
ami-val tests that the instance uses systemctl. As cloud-image-val does not support rhel-6 or lower, this is not necessary.
=> add test_sshd

cloud-image-val.py, main/cloud_image_validator.py, pytest.ini, test/test_cloud_image_validator.py, test/test_suite_runner.py, test_suite/cloud/test_aws.py, test_suite/conftest.py, test_suite/generic/test_generic.py, test_suite/suite_runner.py
Added rhel_only fixture and updated tests cases that are only applicable to RHEL images.
Marked test cases as "pub", which are only applicable to published cloud images.
Improved HTML report with new summary element to know which markers have been used.
Improved HTML report column "Test Case" so that it displays a shorter name of the test executed.
=> Added markers option to run tests matching pytest markers expression.

test_suite/generic/test_generic.py
test_release_version had two assertions. One of them was related to the
image name, which only makes sense in published images. Divide test so
we can use the 'pub' mark.
Also add `rhel_only` fixture to `test_wheel_group_not_set_to_default_use`
=> divide test_release_version in two different tests

test_suite/cloud/test_aws.py
if service is not installed, the test will report an error. But if the
service is not installed we don't need to check if it's disabled. In
this case the test should pass without any checks
=> test_rh_cloud_firstboot_service_is_disabled error

test_suite/cloud/test_aws.py
test_rh_cloud_firstboot_service_is_disabled fails as `is_valid` creates an assertion error instead of returning 1 or 0.
=> test_rh_cloud_firstboot_service_is_disabled assertion error

test_suite/generic/test_generic.py
remove all mark, so this test runs only on rhel and centos
=> test test_sysconfig_kernel does not apply to fedora

cloud/sample/resources_azure_vhd.json, cloud/terraform/azure_config_builder.py
This update brings the possibility of deploying Azure VMs directly from a vhd blob URI.
The Terraform Controller will create an image based on a given vhd, and then create the VM based on that image.
=> Improved azure config builder

.github/workflows/trigger-gitlab.yml, .gitlab-ci.yml, schutzbot/update_github_status.sh
github actions has some limitations that can be solved by having a
parallel gitlab repo intended to run part of the CI.
=> add parallel gilab repository

cloud/terraform/aws_config_builder.py, cloud/terraform/azure_config_builder.py, cloud/terraform/base_config_builder.py
this way, cloud cleaner can remove the leftover resources in case the is
any
=> add ci tag to every azure resource

README.md, cloud/terraform/aws_config_builder.py, test_suite/cloud/test_aws.py
from now on CIV will use env varibles to authenticate into aws. Removing
the profile lets us use containers.
=> remove profile from aws command

test_suite/cloud/test_aws.py
this test in aws has been failing due to images taking too much time to
boot (~55s instead of the previous max, 50s). raising limit to 60s
=> update first_boot max time

lib/test_lib.py, test_suite/cloud/test_azure.py
Also added a test_util function to filter log files. It will be useful
for similar test cases (in os-tests there was also an auxiliary function
for that).
=> Migrated test_check_waagent_log from os-tests.

test_suite/cloud/test_aws.py
We believe this can avoid overloading stdout and resulting in unexpected -1
return code (testinfra module issue).
=> Suppressed output of dnf command when installing lshw utility.

test_suite/cloud/test_aws.py
rhel 8.4 has an old version of cloud-init, which create hostkey files
with wrong permissions. See COMPOSER-1654 for reference.
=> disable test_host_key_permissions on rhel 8.4

test_suite/cloud/test_azure.py
This decision was made internally after discussing with another QE Team.
They confirmed this are functional tests that are not in the scope of
image validation tests.
=> Removed test_waagent_log test case.

test_suite/cloud/test_aws.py, test_suite/generic/test_generic.py
Also removed the ami-val test equivalent previously migrated,
that was only being run on AWS instances. The test is now generic.
=> Migrated test_check_nm_cloud_setup test from os-tests.

cloud/terraform/aws_config_builder.py, cloud/terraform/gcloud_config_builder.py, test_suite/generic/test_generic.py
Also changed the default instance type for AWS and GCP.
If the instance has 1GB or less, kdump serive fails to start
due to memory allocation issues.
Test names from os-tests:
- test_check_kdump_configuration
- test_check_kdump_status
=> Migrated kdump-related test cases, from os-tests.

.gitlab-ci.yml, test_suite/cloud/test_aws.py, test_suite/generic/test_generic.py
Check bugzilla in test docstring. This test only applies to aws not
other clouds (at least it seems so)
=> test_timezone_is_utc only applies to aws

.gitlab-ci.yml
To follow container registries conventions, we'll use :latest tag for
the last build instead of main.
=> use :latest tag instead of :main

.gitlab-ci.yml
This way, the container image will be published as long as IB test are
green. In the medium term, we have to solve this errors and enable this
tests again
=> temporarily disable pub tests on main

test_suite/generic/test_generic.py
The package kexec-tools updated kdump configuration in version 2.0.24-3,
adding a new argument to a line. Update the test case.
package changelog: https://brewweb.engineering.redhat.com/brew/buildinfo?buildID=2089350
=> kdump configuration update

test_suite/generic/test_generic.py
Two tests from the test suite were failing when running CIV on aarch64 VMs. Solve them.
=> Solve two bugs on aarch64

test_suite/generic/test_generic.py
Two tests from the test suite were failing when running CIV on aarch64 VMs. Solve them.
=> enabling aarch64 testing coused a fes bugs

lib/console_lib.py, test_suite/generic/test_generic.py
crashkernel_is_enabled_rhel is failing because the configuration changed. to avoid having to maintain the test everytime the config changes, check `kdumpctl showmem` instead
=> test_suite: crashkernel_is_enabled bug

main/cloud_image_validator.py
if terraform init failed, the job reported a pass. Fix the bug
=> main: solve terraform init fail bug

test_suite/cloud/test_azure.py
fedora has different setting for `minclass`. Add this exception to the test
=> test_suite: fix test_pwquality_conf for fedora

test_suite/cloud/test_azure.py, test_suite/generic/test_generic.py
When CIV tool was included in azure.sh (osbuild-composer), some test were failing in 8.7 and 9.1 (due to not having appropiate CI setup, won't happen in the near future). Temporarily disable these tests so we can solve them insinde CIV repo.
=> test_suite: disable some tests (failing nightlies)

schutzbot/deploy.sh
dependabot commits do not trigger CI. this means there are no published RPMs even though the commit is marked as passed. Add a condition to skip dependabot commits
=> dependabot: fix get_last_passed_commit

schutzbot/deploy.sh
Fix yet again this function. generalized so only commits with passing gitlab CI will be used
=> Schutzbot: fix get_last_passed_commit

test_suite/cloud/test_azure.py, test_suite/generic/test_generic.py
Failing tests where disabled so we could debug them in CIV repo instead of osbuild-composer (CLOUDX-211). Enable them and solve them
=> test_suite: enable nightly failing tests

lib/ssh_lib.py
If the terraform controller timed out when trying to connect to the instances, it whould exit.
=> lib: exit on instance timeout

test_suite/cloud/test_aws.py
In some AWS regions, some CDS hosts are not available. Also, there are others that have connectivity issues or simply are being deprecated (e.g. rhui2). So, the logic was enhanced to check first the newest ones and print the ones that are failing to communicate with the instance. Lastly, the logic checks all of the CDS and the test now fails only if ALL of them are unavailable.
=> Fix test_redhat_cds_hostnames test case.

README.md
A new feature for 'exclude_on' marker has been added which helps to skip versions in a range under or bigger then a specified version, with a help of the opeartors ('<' or '>').
=> CIV: Update readme file

.gitlab-ci.yml
This is due to lack of clarity in the images to be tested from cloud marketplaces. Once we have it clear, we will re-enable these jobs and update the resources.json files used for this purpose. Now we will rely on ImageBuilder integration to test our code.
=> Skip azure and aws jobs in gitLab CI.

test_suite/generic/test_generic.py
This test case was being run on RHEL lower than 8.4 since the exclusion logic was only applying to RHEL 8.4 This needs to be excluded in ANY RHEL version lover than 8.5.
=> Fix test_network_manager_cloud_setup

requirements.txt, test/test_suite_runner.py, test_suite/suite_runner.py
This is a previous step to unblock other use cases to process test report data such as the CIV Report Analyzer tool we are developing right now.
=> Add a JSON report as part of the artifacts generated by the tool.

cloud/terraform/aws_config_builder.py
This test case is sometimes failing due to lack of RAM in the running instance. By setting an instance type with more resources, this should be fixed. This test also indirectly fixed test_no_fail_service test case, since this latter one is also failing when kdump did not work as expected.
=> Fix test_kdump_status test case.

.gitlab-ci.yml
In order to use different options when running aws.sh from CIV CI, we are now using a variable to specify this. This is done to start the work for CLOUDX-345
=> Add new variable with CIV options

cloud/terraform/azure_config_builder_v2.py
This is due to inconsistencies when choosing VM architecture.
=> Fix Azure arm64 deployment.

cloud/terraform/terraform_controller.py
Since adding ap-southeast-4 regions, those instances are timing out. Trying to see if this is the reason
=> Modify timeout for ssh

README.md
Use the latest image from `quay.io/cloudexperience/cloud-image-val`.
=> Fix the container image name in the README file

cloud/terraform/base_config_builder.py, cloud/terraform/gcloud_config_builder.py
Google Cloud uses labels instead of tags.
=> Support tagging of Google Cloud resources

main/civ_report_analyzer.py, test_suite/generic/test_generic.py
This logic is now checking if the AWS region of the running instance is actually supported or not. The list of supported and unsupported regions is in a Google Spreadsheet created by the RHUI Team: https://docs.google.com/spreadsheets/d/15bcP0a9fBaxHVbk6tXiBL8Hn5fLjkHx9GjNf06ctISI/
=> Improved logic when testing subscription manager.

test/test_suite_runner.py, test_suite/generic/test_generic.py, test_suite/suite_runner.py
This PR increases the maximum number of concurrent threads for testing in parallel. Before it was limited to 40 but we usually test more than 160 images at the same time in our automation, so it is taking 1 hour in total.
With this change, based on the latest testing, we are reducing suite runner execution time by ~64%. So, it is 2/3 faster than before.
However we are still limited by Terraform during deployment and even though we will increase the parallelism value (in the Jenkins pipeline), we may be still limited by the cloud provider's API calls limit or the SDK implementation that Terraform uses in the backend.
=> Improve CIV performance for automation

test_suite/generic/test_generic.py
Until it is investigated why it fails on RHEL 9.3 and then fixed.
=> Skip test_networkmanager_conf_plugins.

cloud/terraform/aws_config_builder.py, cloud/terraform/azure_config_builder_v2.py
Now the ".sp" part is optional.
Also fixed an issue with resource tagging in AWS.
=> Fixed regex to detect Azure image vhd blob metadata from URL.

cloud-image-val.py, lib/config_lib.py, main/cloud_image_validator.py, test/test_cloud_image_validator.py
For this, we refactored the CIVConfig class and changed the behavior to allow combined options (a config file and some params to override what is already present in the config). Also, if the config file does not exist, it will always be created with default values and then updated with the values provided via cli params.
=> Added cli params preference over config file.

test_suite/generic/test_generic.py
The fix consists in actually skipping the test case starting from RHEL 9.3, since cloud-init does not touch NM config anymore, and the plugins are the ones that come by default along with the rpm package.
Also added more context to the test case stdout.
=> Fixed test_networkmanager_conf_plugins which was failing in RHEL 9.3.

requirements.txt
In the past days there was a bug affecting pytest. This was reported and tracked here:
* https://github.com/yaml/pyyaml/issues/724
The proposed solution was to downgrade PyYAML to 5.3.1 until it was resolved. Now this issue is fixed in PyYAML, however there are still no updates from pytest, which is currently in v7.4.0 (last update in June 23 2023).
Until they update this in next release, we will force PyYAML 5.3.1 to be installed before pytest in our project dependencies.
In this PR we also take the opportunity to update pytest-testinfra to benefit from stability and performance improvements.
=> Fixed dependencies issues with PyYAML and pytest.

test_suite/cloud/test_aws.py
=> Add a test to assert on /etc/machine-id permissions for AWS

requirements.txt, test_suite/cloud/test_aws.py, test_suite/cloud/test_azure.py, test_suite/conftest.py, test_suite/generic/test_generic.py
Before we were comparing floats, but it turns out that it is not accurate, since in the case of RHEL 8.10, it is semantically greater than e.g. 8.4, however if they are compared as float, 8.4 is greater than 8.10.
=> Fixed version comparisons in all the test suites and conftest.py

lib/test_lib.py, test_suite/generic/test_generic.py
Also improved test_lib.print_host_command_output() function to return the command result object so that we don't re-run commands when printing and handling output data at the same time.
=> Improved output of test_no_avc_denials test case for better debugging.

test_suite/cloud/test_aws.py
Need to add a new condition for both 9.4 and 8.10 distros with new hashes.
=> CIV: fix for audit.conf test

cloud/terraform/azure_config_builder_v2.py
An osbuild-composer PR#3887 [1] introduces "dot-notation" for distro versions, meaning that a dot will be used to separate major and minor version in distro names. For backward compatibility, distro names without a dot will be still accepted for distros which used to accept it.
The CIV code parsing a VHD name was not expecting the version to contain any dot. This results in failures such as [2].
Modify the regular expression to gracefully handle potential dot in the version string.
[1] https://github.com/osbuild/osbuild-composer/pull/3887
[2] https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/jobs/5943494707#L3695
=> AzureConfigBuilderV2: gracefully handle dot in release versions

test_suite/generic/test_generic.py
Hi,
It seems, that generic check **test_cloud_cfg()** always **PASS**, because **_rpm -V_** only returns **_0_** or **_1_** which makes **host.run_test()** always succeed.
The proposal is to check modification flags of **/etc/cloud/cloud.cfg** in a more accurate way:
`rpm -Vf /etc/cloud/cloud.cfg | grep -e "^S.5.*/etc/cloud/cloud.cfg$"`
=> Use correct detection of modified cfg in test_cloud_cfg()

test_suite/generic/test_generic.py
Related JIRA: CLOUDX-812. These images were not built by image builder and do not contain the changes we check in the test case.
=> Skipped test_cloud_configs test case in RHEL-SAP 8.4 and older.

test_suite/generic/test_generic.py
RHEL-24346: NetworkManager causing avc denials, to be fixed on RHEL-9.5.
=> Skipped test_no_avc_denials test case due to a known issue.

cloud-image-val.py, lib/config_lib.py, main/cloud_image_validator.py, test/test_cloud_image_validator.py, test/test_suite_runner.py, test_suite/suite_runner.py
It is an optional argument/config value. If not used, behavior will remain the same. 
This means that we still hardcode the default test suite paths which belong to test_suite/cloud and test_suite/generic directories.
=> Added new param/config to specify custom test suite paths.

cloud/terraform/terraform_configurator.py
It was crashing in the case there were no tagas at all. So it was trying to find values in  NoneType.
We didn't notice this in the CI since we always use tags.
=> Fixed tags check for AWS deployments.

cloud/opentofu/opentofu_controller.py
to make it more consistent with osbuild-composer's own test suite and to allow for some VMs which seem to be a bit slow to start.
=> Increase waiting time for SSH up to 5 mins

test_suite/generic/test_generic.py
Newer versions of osbuild & images quote environment variables in systemd unit files.
Fixes #310
=> test_network_manager_cloud_setup: allow alternate quoting

test_suite/cloud/test_aws.py
We now check for the correct packages for RHEL-SAP in its dedicated module.
=> Fixed test_required_packages_are_installed test case.

test_suite/cloud/test_aws.py
https://issues.redhat.com/browse/CLOUDX-837
=> CIV: Refactor test_yum_group_install

lib/aws_lib.py, test_suite/cloud/test_aws.py, test_suite/conftest.py, test_suite/generic/test_generic.py
These changes are part of CLOUDX-993, to adapt our tooling to deal with recent changes that have merged all type of AMIs together in the same testing request.
=> Added logic for RHEL AWS Stratosphere images.

ci/aws.sh
This allows the aws.sh script to finish gracefully in the event no test cases were collected because the filters used actually did not select any applicable test (e.g. "pub" marked tests for Image Builder internal CI).
Also added extra checks for infrastructure-related issues such as when CIV exits with code 100 (introduced by us to identify deployment issues).
=> Added better exit code checks for CIV execution.

test_suite/generic/test_generic.py
=> COMPOSER-2437: Skip test_eth0_network_adapter_setup

test_suite/cloud/test_aws.py, test_suite/generic/test_generic.py
Closes [CLOUDX-979](https://issues.redhat.com/browse/CLOUDX-979)
=> add net.ifnames absence on rhel10 test

test_suite/cloud/test_aws.py
This is to fix a test which fails for RHEL10 on AWS as net.ifnames=0 is deprecated there.
In the future it's desired to unite two test on net.ifnames=0 as reported in [CLOUDX-1303](https://issues.redhat.com/browse/CLOUDX-1303)
=> remove net.ifnames=0 check for rhel10

test_suite/cloud/test_aws.py
gdisk retired in RHEL10 as per RHELMISC-6651
=> exclude rhel10 in dracut_cinf_sgdisk test

test_suite/generic/test_generic.py
In RHEL10, passwd lock is noted as "L", not "LK" as in earlier releases.
=> change root lock test for rhel10

test_suite/cloud/test_aws.py, test_suite/cloud/test_azure.py
Remove dhcp-client and gdisk from the list of required installed packages in RHEL10
Also remove EOL releases in the corresponding required installed packages test.
RHELMISC-4466 dhcp-client retired in RHEL10
RHELMISC-6651 gdisk retired in RHEL10
Contributes to [CLOUDX-1302](https://issues.redhat.com/browse/CLOUDX-1302)
=> dhcp-client and gdisk retired in rhel10

test_suite/cloud/test_azure.py
By mistake I copy pasted removal of the dhcp-client on Azure, while it was for AWS only, and in general dhcp-client never was on Azure, therefore taking it back.
=> dhcp-client removal never needed for azure

test_suite/generic/helpers.py
There is a known issue with avc denial in irqbalance (RHEL-78630), which we need to ignore for now for our and osbuild-composer CIs to pass.
=> ignore avc denial for irqbalance

test_suite/generic/test_generic.py
The exclude marker set to a major version didn't work with 10.0, therefore changing it to a minor version.
=> update exclude marker to a minor version

test_suite/generic/test_generic.py
In [PR#392](https://github.com/osbuild/cloud-image-val/pull/392) in [this line](https://github.com/osbuild/cloud-image-val/pull/392/files#diff-6e493f324d72e518b7e1570ff75ebdad6f8125756bd4e28e6bbc9cb7f413cbabL910), I removed exclude marker pointing to a Jira ticket for smartcard-auth pam file content which was marked for an issue for RHEL8.9 which is EOL. That PR merge happened while a part of our CI was down and we were not aware of it yet, and it resulted in a false positive. Now, when our CI back fully we see it fails on 8.10 GA. Therefore, returning that exclude marker back.
=> return accidenly removed skip on smartcard_auth test

data/generic/smartcard-auth_rhel8.10, test_suite/generic/test_generic.py
Since the changes in a PAM file were introduced starting from 8.9, and it's EOL we check 8.10 exceptionally only. 
For other releases / minor versions anything stays intact-ed.
Fix #398 
@F-X64 one more please.  =D It was faster than anticipated.
=> fix smartcard-auth test for 8.10

lib/ssh_lib.py
[PR371](https://github.com/osbuild/cloud-image-val/pull/371)  changed the tool used to create ssh keys. ssh-keygen sets correct permissions on the private part of a key - 600, meanwhile rsa from cryptography uses the system umask. 
It resulted in wrong permissions used, and consequently the team's keys couldn't be copied on created VMs. 
Fix [CLOUDX-1301](https://issues.redhat.com/browse/CLOUDX-1301)
=> set correct key permissions

test_suite/cloud/test_azure.py
Retire hypervfcopyd in RHEL10 aarch64 on Azure
Close [CLOUDX-1335](https://issues.redhat.com/browse/CLOUDX-1335)
=> retire hypervfcopyd in RHEL10 aarch64

test_suite/generic/test_generic.py
Test the installation of the system-reinstall-bootc package on 9.6 and 10.0
Close [CLOUDX-1267](https://issues.redhat.com/browse/CLOUDX-1267)
- adds a new test case checking the system-reinstall-bootc is installed
=> add bootc installed test

test_suite/generic/test_generic.py
If /boot exists, it should be at least 960MiB as a lower threshold of 1024Mib
=> test /boot size being >=960MiB

test_suite/cloud/test_azure.py
aarch64 Azure images should have 'console=ttyAMA0' in grub params instead of others. 
Starting with 9.6 and 10.0, there should be 'nvme_core.io_timeout=240' for all arch.
=> change grub param for azure
